### ISSUE TITLE
Broken on latest php buildpack

### ISSUE THREAD

**Issue by longnguyen11288** [dmikusa-pivotal/cf-ex-wordpress#5]
Looks like latest php buildpack breaks this extension.py for wordpress, I haven't had time to investigate why but this seem to be https://github.com/cloudfoundry/php-buildpack/commit/a5dfad3d36965b3975bc045c1b02a197f9b47ba8 when it all changed around.

**Comment by dmikusa-pivotal** [comment]
Yes, apologizes.  See this [issue](https://github.com/cloudfoundry/php-buildpack/issues/55) for details.

One workaround is to use a slightly older variation of the build pack. You can do this with the -b argument to cf push or with the buildpack attribute in your manifest.yml file.

Ex: `buildpack: https://github.com/cloudfoundry/php-buildpack#8c13f5434b2f31ca960d2bca9153df1978258535`

**Comment by dmikusa-pivotal** [comment]
I pushed this change to the example, so it should use the older build pack by default now.

**Comment by longnguyen11288** [comment]
Yeah i ended up using older buildpack
