### ISSUE TITLE
Add license information for this project?

### ISSUE THREAD

**Issue by brittag** [dmikusa-pivotal/cf-ex-wordpress#7]
While looking into improving the documentation for my work team's [fork of this project](https://github.com/18F/cf-ex-wordpress), I looked for a license statement in this repository so that I could include that information in our fork, and I couldn't find license information here. I'd like to provide a note in our fork about the open source license of this work (and our team's modifications) so that other people can feel fully welcome to reuse/adapt our fork if they like.

@dmikusa-pivotal, as the main author, would you consider adding a note to this readme (or a license file) to indicate the license you'd like this to be under?

Thank you!

**Comment by dmikusa-pivotal** [comment]
Sorry for not adding that sooner.  [Done](https://github.com/dmikusa-pivotal/cf-ex-wordpress/commit/5bdf86ca94b0449690afc9b8b15b9f6867974c3a).

**Comment by brittag** [comment]
Yay, thank you very much!
